default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: blogs_development

test:
  <<: *default
  database: blogs_test

production:
  <<: *default
  database: blogs_production
  username: blogs
  password: <%= ENV['BLOGS_DATABASE_PASSWORD'] %>
